name: Auto Update 1
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install unzip and Python dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          pip install requests

      - name: Unzip tv-logo-main.zip
        run: unzip -o tv-logo-main.zip -d ./unzipped

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -r ./unzipped/* .
          git add .
          git commit -m "Auto update from zip file" || echo "No changes to commit"
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write
