Skip to content
Navigation Menu
abusaeeidx
CricHd-playlists-Auto-Update-permanent

Code
Issues
Pull requests
Actions
Projects
Security
Insights
Auto Update 1
Auto Update 1 #1244
Jobs
Run details
Workflow file for this run
.github/workflows/blank.yml at 4755334
name: Auto Update 1
# জীবনে শুধু চুরি করা ছাড়া আর কিছু শিখলি না। 
 #এটা আপনার পারিবারিক শিক্ষা।
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD2 }} run.zip

      - name: Run Python Script
        run: python run.py

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api.json ALL.m3u
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto update api.json and ALL.m3u"
      - name: Push Changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

permissions:
  contents: write
Auto update api.json and ALL.m3u · abusaeeidx/CricHd-playlists-Auto-Update-permanent@4755334 
