name: Extract GitHub Logo ZIP

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: List files (debug)
        run: ls -la

      - name: Run Extract Script
        run: python extract_zip.py
